// ============================================
// BBS Office Database - Auto-complete Data
// Bangladesh Bureau of Statistics
// Total Offices: 565
// Generated: 2026-04-26
// ============================================

const bbsOffices = [
  { bn: "সেন্সাস উইং, বিবিএস, ঢাকা", en: "Census Wing, BBS, Dhaka", type: "HQ Wing" },
  { bn: "কৃষি উইং, বিবিএস, ঢাকা", en: "Agriculture Wing, BBS, Dhaka", type: "HQ Wing" },
  { bn: "শিল্প ও শ্রম উইং, বিবিএস, ঢাকা", en: "Industry and Labour Wing, BBS, Dhaka", type: "HQ Wing" },
  { bn: "জাতীয় হিসাব উইং, বিবিএস, ঢাকা", en: "National Accounting Wing, BBS, Dhaka", type: "HQ Wing" },
  { bn: "জনসংখ্যা ও স্বাস্থ্য উইং, বিবিএস, ঢাকা", en: "Demography and Health Wing, BBS, Dhaka", type: "HQ Wing" },
  { bn: "কম্পিউটার উইং, বিবিএস, ঢাকা", en: "Computer Wing, BBS, Dhaka", type: "HQ Wing" },
  { bn: "অর্থ, প্রশাসন ও ব্যবস্থাপনা তথ্য ব্যবস্থা (FA & MIS) উইং, বিবিএস, ঢাকা", en: "Finance, Administration and MIS Wing, BBS, Dhaka", type: "HQ Wing" },
  { bn: "পরিসংখ্যান কর্মী প্রশিক্ষণ ইনস্টিটিউট (SSTI), বিবিএস, ঢাকা", en: "Statistical Staff Training Institute (SSTI), BBS, Dhaka", type: "HQ Wing" },
  { bn: "পরিকল্পনা ও উন্নয়ন সেল, বিবিএস, ঢাকা", en: "Planning and Development Cell, BBS, Dhaka", type: "HQ Wing" },
  { bn: "প্রকাশনা উইং, বিবিএস, ঢাকা", en: "Publication Wing, BBS, Dhaka", type: "HQ Wing" },
  { bn: "বিভাগীয় পরিসংখ্যান অফিস, ঢাকা", en: "Divisional Statistical Office, Dhaka", type: "Divisional" },
  { bn: "বিভাগীয় পরিসংখ্যান অফিস, চট্টগ্রাম", en: "Divisional Statistical Office, Chattogram", type: "Divisional" },
  { bn: "বিভাগীয় পরিসংখ্যান অফিস, রাজশাহী", en: "Divisional Statistical Office, Rajshahi", type: "Divisional" },
  { bn: "বিভাগীয় পরিসংখ্যান অফিস, খুলনা", en: "Divisional Statistical Office, Khulna", type: "Divisional" },
  { bn: "বিভাগীয় পরিসংখ্যান অফিস, বরিশাল", en: "Divisional Statistical Office, Barishal", type: "Divisional" },
  { bn: "বিভাগীয় পরিসংখ্যান অফিস, সিলেট", en: "Divisional Statistical Office, Sylhet", type: "Divisional" },
  { bn: "বিভাগীয় পরিসংখ্যান অফিস, রংপুর", en: "Divisional Statistical Office, Rangpur", type: "Divisional" },
  { bn: "বিভাগীয় পরিসংখ্যান অফিস, ময়মনসিংহ", en: "Divisional Statistical Office, Mymensingh", type: "Divisional" },
  { bn: "জেলা পরিসংখ্যান অফিস, বাগেরহাট", en: "District Statistical Office, Bagerhat", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, বান্দরবান", en: "District Statistical Office, Bandarban", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, বরগুনা", en: "District Statistical Office, Barguna", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, বরিশাল", en: "District Statistical Office, Barishal", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, ভোলা", en: "District Statistical Office, Bhola", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, বগুড়া", en: "District Statistical Office, Bogura", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, ব্রাহ্মণবাড়িয়া", en: "District Statistical Office, Brahmanbaria", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, চাঁদপুর", en: "District Statistical Office, Chandpur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, চাঁপাইনবাবগঞ্জ", en: "District Statistical Office, Chapainawabganj", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, চট্টগ্রাম", en: "District Statistical Office, Chattogram", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, চুয়াডাঙ্গা", en: "District Statistical Office, Chuadanga", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, কক্সবাজার", en: "District Statistical Office, Cox's Bazar", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, কুমিল্লা", en: "District Statistical Office, Cumilla", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, ঢাকা", en: "District Statistical Office, Dhaka", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, দিনাজপুর", en: "District Statistical Office, Dinajpur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, ফরিদপুর", en: "District Statistical Office, Faridpur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, ফেনী", en: "District Statistical Office, Feni", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, গাইবান্ধা", en: "District Statistical Office, Gaibandha", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, গাজীপুর", en: "District Statistical Office, Gazipur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, গোপালগঞ্জ", en: "District Statistical Office, Gopalganj", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, হবিগঞ্জ", en: "District Statistical Office, Habiganj", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, জয়পুরহাট", en: "District Statistical Office, Joypurhat", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, জামালপুর", en: "District Statistical Office, Jamalpur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, ঝালকাঠি", en: "District Statistical Office, Jhalokati", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, ঝিনাইদহ", en: "District Statistical Office, Jhenaidah", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, খাগড়াছড়ি", en: "District Statistical Office, Khagrachhari", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, খুলনা", en: "District Statistical Office, Khulna", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, কিশোরগঞ্জ", en: "District Statistical Office, Kishoreganj", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, কুড়িগ্রাম", en: "District Statistical Office, Kurigram", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, কুষ্টিয়া", en: "District Statistical Office, Kushtia", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, লক্ষ্মীপুর", en: "District Statistical Office, Lakshmipur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, লালমনিরহাট", en: "District Statistical Office, Lalmonirhat", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, মাদারীপুর", en: "District Statistical Office, Madaripur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, মাগুরা", en: "District Statistical Office, Magura", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, মানিকগঞ্জ", en: "District Statistical Office, Manikganj", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, মেহেরপুর", en: "District Statistical Office, Meherpur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, মৌলভীবাজার", en: "District Statistical Office, Moulvibazar", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, মুন্সীগঞ্জ", en: "District Statistical Office, Munshiganj", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, ময়মনসিংহ", en: "District Statistical Office, Mymensingh", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, নওগাঁ", en: "District Statistical Office, Naogaon", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, নড়াইল", en: "District Statistical Office, Narail", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, নারায়ণগঞ্জ", en: "District Statistical Office, Narayanganj", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, নরসিংদী", en: "District Statistical Office, Narsingdi", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, নাটোর", en: "District Statistical Office, Natore", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, নেত্রকোনা", en: "District Statistical Office, Netrokona", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, নীলফামারী", en: "District Statistical Office, Nilphamari", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, নোয়াখালী", en: "District Statistical Office, Noakhali", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, পাবনা", en: "District Statistical Office, Pabna", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, পঞ্চগড়", en: "District Statistical Office, Panchagarh", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, পটুয়াখালী", en: "District Statistical Office, Patuakhali", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, পিরোজপুর", en: "District Statistical Office, Pirojpur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, রাজবাড়ী", en: "District Statistical Office, Rajbari", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, রাজশাহী", en: "District Statistical Office, Rajshahi", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, রাঙ্গামাটি", en: "District Statistical Office, Rangamati", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, রংপুর", en: "District Statistical Office, Rangpur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, সাতক্ষীরা", en: "District Statistical Office, Satkhira", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, শরীয়তপুর", en: "District Statistical Office, Shariatpur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, শেরপুর", en: "District Statistical Office, Sherpur", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, সিরাজগঞ্জ", en: "District Statistical Office, Sirajganj", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, সুনামগঞ্জ", en: "District Statistical Office, Sunamganj", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, সিলেট", en: "District Statistical Office, Sylhet", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, টাঙ্গাইল", en: "District Statistical Office, Tangail", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, ঠাকুরগাঁও", en: "District Statistical Office, Thakurgaon", type: "District" },
  { bn: "জেলা পরিসংখ্যান অফিস, যশোর", en: "District Statistical Office, Jashore", type: "District" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ধামরাই, Dhaka", en: "Upazila Statistical Office, Dhamrai, Dhaka", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দোহার, Dhaka", en: "Upazila Statistical Office, Dohar, Dhaka", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কেরানীগঞ্জ, Dhaka", en: "Upazila Statistical Office, Keraniganj, Dhaka", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নবাবগঞ্জ, Dhaka", en: "Upazila Statistical Office, Nawabganj, Dhaka", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সাভার, Dhaka", en: "Upazila Statistical Office, Savar, Dhaka", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আলফাডাঙ্গা, Faridpur", en: "Upazila Statistical Office, Alfadanga, Faridpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভাঙ্গা, Faridpur", en: "Upazila Statistical Office, Bhanga, Faridpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বোয়ালমারী, Faridpur", en: "Upazila Statistical Office, Boalmari, Faridpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চরভদ্রাসন, Faridpur", en: "Upazila Statistical Office, Charbhadrasan, Faridpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফরিদপুর সদর, Faridpur", en: "Upazila Statistical Office, Faridpur Sadar, Faridpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মধুখালী, Faridpur", en: "Upazila Statistical Office, Madhukhali, Faridpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নগরকান্দা, Faridpur", en: "Upazila Statistical Office, Nagarkanda, Faridpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সদরপুর, Faridpur", en: "Upazila Statistical Office, Sadarpur, Faridpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সালথা, Faridpur", en: "Upazila Statistical Office, Saltha, Faridpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গাজীপুর সদর, Gazipur", en: "Upazila Statistical Office, Gazipur Sadar, Gazipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালিয়াকৈর, Gazipur", en: "Upazila Statistical Office, Kaliakair, Gazipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালীগঞ্জ, Gazipur", en: "Upazila Statistical Office, Kaliganj, Gazipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কাপাসিয়া, Gazipur", en: "Upazila Statistical Office, Kapasia, Gazipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শ্রীপুর, Gazipur", en: "Upazila Statistical Office, Sreepur, Gazipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গোপালগঞ্জ সদর, Gopalganj", en: "Upazila Statistical Office, Gopalganj Sadar, Gopalganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কাশিয়ানী, Gopalganj", en: "Upazila Statistical Office, Kashiani, Gopalganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কোটালীপাড়া, Gopalganj", en: "Upazila Statistical Office, Kotalipara, Gopalganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মুকসুদপুর, Gopalganj", en: "Upazila Statistical Office, Muksudpur, Gopalganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, টুঙ্গিপাড়া, Gopalganj", en: "Upazila Statistical Office, Tungipara, Gopalganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, অষ্টগ্রাম, Kishoreganj", en: "Upazila Statistical Office, Austagram, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাজিতপুর, Kishoreganj", en: "Upazila Statistical Office, Bajitpur, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভৈরব, Kishoreganj", en: "Upazila Statistical Office, Bhairab, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হোসেনপুর, Kishoreganj", en: "Upazila Statistical Office, Hossainpur, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ইটনা, Kishoreganj", en: "Upazila Statistical Office, Itna, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, করিমগঞ্জ, Kishoreganj", en: "Upazila Statistical Office, Karimganj, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কটিয়াদী, Kishoreganj", en: "Upazila Statistical Office, Katiadi, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কিশোরগঞ্জ সদর, Kishoreganj", en: "Upazila Statistical Office, Kishoreganj Sadar, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কুলিয়ারচর, Kishoreganj", en: "Upazila Statistical Office, Kuliarchar, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মিঠামইন, Kishoreganj", en: "Upazila Statistical Office, Mithamain, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নিকলী, Kishoreganj", en: "Upazila Statistical Office, Nikli, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পাকুন্দিয়া, Kishoreganj", en: "Upazila Statistical Office, Pakundia, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তাড়াইল, Kishoreganj", en: "Upazila Statistical Office, Tarail, Kishoreganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাজৈর, Madaripur", en: "Upazila Statistical Office, Rajoir, Madaripur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মাদারীপুর সদর, Madaripur", en: "Upazila Statistical Office, Madaripur Sadar, Madaripur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালকিনি, Madaripur", en: "Upazila Statistical Office, Kalkini, Madaripur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শিবচর, Madaripur", en: "Upazila Statistical Office, Shibchar, Madaripur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দৌলতপুর, Manikganj", en: "Upazila Statistical Office, Daulatpur, Manikganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঘিওর, Manikganj", en: "Upazila Statistical Office, Ghior, Manikganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হরিরামপুর, Manikganj", en: "Upazila Statistical Office, Harirampur, Manikganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মানিকগঞ্জ সদর, Manikganj", en: "Upazila Statistical Office, Manikganj Sadar, Manikganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সাটুরিয়া, Manikganj", en: "Upazila Statistical Office, Saturia, Manikganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শিবালয়, Manikganj", en: "Upazila Statistical Office, Shibalaya, Manikganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সিংগাইর, Manikganj", en: "Upazila Statistical Office, Singair, Manikganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গজারিয়া, Munshiganj", en: "Upazila Statistical Office, Gazaria, Munshiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লৌহজং, Munshiganj", en: "Upazila Statistical Office, Lohajang, Munshiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মুন্সীগঞ্জ সদর, Munshiganj", en: "Upazila Statistical Office, Munshiganj Sadar, Munshiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শ্রীনগর, Munshiganj", en: "Upazila Statistical Office, Sreenagar, Munshiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, টংগীবাড়ী, Munshiganj", en: "Upazila Statistical Office, Tongibari, Munshiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আড়াইহাজার, Narayanganj", en: "Upazila Statistical Office, Araihazar, Narayanganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বন্দর, Narayanganj", en: "Upazila Statistical Office, Bandar, Narayanganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নারায়ণগঞ্জ সদর, Narayanganj", en: "Upazila Statistical Office, Narayanganj Sadar, Narayanganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রূপগঞ্জ, Narayanganj", en: "Upazila Statistical Office, Rupganj, Narayanganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সোনারগাঁও, Narayanganj", en: "Upazila Statistical Office, Sonargaon, Narayanganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বেলাবো, Narsingdi", en: "Upazila Statistical Office, Belabo, Narsingdi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মনোহরদী, Narsingdi", en: "Upazila Statistical Office, Monohardi, Narsingdi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নরসিংদী সদর, Narsingdi", en: "Upazila Statistical Office, Narsingdi Sadar, Narsingdi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পলাশ, Narsingdi", en: "Upazila Statistical Office, Palash, Narsingdi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রায়পুরা, Narsingdi", en: "Upazila Statistical Office, Raipura, Narsingdi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শিবপুর, Narsingdi", en: "Upazila Statistical Office, Shibpur, Narsingdi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বালিয়াকান্দি, Rajbari", en: "Upazila Statistical Office, Baliakandi, Rajbari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গোয়ালন্দ, Rajbari", en: "Upazila Statistical Office, Goalanda, Rajbari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পাংশা, Rajbari", en: "Upazila Statistical Office, Pangsha, Rajbari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাজবাড়ী সদর, Rajbari", en: "Upazila Statistical Office, Rajbari Sadar, Rajbari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালুখালী, Rajbari", en: "Upazila Statistical Office, Kalukhali, Rajbari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভেদরগঞ্জ, Shariatpur", en: "Upazila Statistical Office, Bhedarganj, Shariatpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ডামুড্যা, Shariatpur", en: "Upazila Statistical Office, Damudya, Shariatpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গোসাইরহাট, Shariatpur", en: "Upazila Statistical Office, Gosairhat, Shariatpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নড়িয়া, Shariatpur", en: "Upazila Statistical Office, Naria, Shariatpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শরীয়তপুর সদর, Shariatpur", en: "Upazila Statistical Office, Shariatpur Sadar, Shariatpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জাজিরা, Shariatpur", en: "Upazila Statistical Office, Zajira, Shariatpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাসাইল, Tangail", en: "Upazila Statistical Office, Basail, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভুয়াপুর, Tangail", en: "Upazila Statistical Office, Bhuapur, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দেলদুয়ার, Tangail", en: "Upazila Statistical Office, Delduar, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ধনবাড়ী, Tangail", en: "Upazila Statistical Office, Dhanbari, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঘাটাইল, Tangail", en: "Upazila Statistical Office, Ghatail, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গোপালপুর, Tangail", en: "Upazila Statistical Office, Gopalpur, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালিহাতী, Tangail", en: "Upazila Statistical Office, Kalihati, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মধুপুর, Tangail", en: "Upazila Statistical Office, Madhupur, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মির্জাপুর, Tangail", en: "Upazila Statistical Office, Mirzapur, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নাগরপুর, Tangail", en: "Upazila Statistical Office, Nagarpur, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সখিপুর, Tangail", en: "Upazila Statistical Office, Sakhipur, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, টাঙ্গাইল সদর, Tangail", en: "Upazila Statistical Office, Tangail Sadar, Tangail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আনোয়ারা, Chattogram", en: "Upazila Statistical Office, Anwara, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাঁশখালী, Chattogram", en: "Upazila Statistical Office, Banshkhali, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বোয়ালখালী, Chattogram", en: "Upazila Statistical Office, Boalkhali, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চন্দনাইশ, Chattogram", en: "Upazila Statistical Office, Chandanaish, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফটিকছড়ি, Chattogram", en: "Upazila Statistical Office, Fatikchhari, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হাটহাজারী, Chattogram", en: "Upazila Statistical Office, Hathazari, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লোহাগাড়া, Chattogram", en: "Upazila Statistical Office, Lohagara, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মীরসরাই, Chattogram", en: "Upazila Statistical Office, Mirsharai, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পটিয়া, Chattogram", en: "Upazila Statistical Office, Patiya, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাঙ্গুনিয়া, Chattogram", en: "Upazila Statistical Office, Rangunia, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাউজান, Chattogram", en: "Upazila Statistical Office, Raozan, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সন্দ্বীপ, Chattogram", en: "Upazila Statistical Office, Sandwip, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সাতকানিয়া, Chattogram", en: "Upazila Statistical Office, Satkania, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সীতাকুণ্ড, Chattogram", en: "Upazila Statistical Office, Sitakunda, Chattogram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আলীকদম, Bandarban", en: "Upazila Statistical Office, Alikadam, Bandarban", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বান্দরবান সদর, Bandarban", en: "Upazila Statistical Office, Bandarban Sadar, Bandarban", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লামা, Bandarban", en: "Upazila Statistical Office, Lama, Bandarban", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নাইক্ষ্যংছড়ি, Bandarban", en: "Upazila Statistical Office, Naikhongchhari, Bandarban", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রোয়াংছড়ি, Bandarban", en: "Upazila Statistical Office, Rowangchhari, Bandarban", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রুমা, Bandarban", en: "Upazila Statistical Office, Ruma, Bandarban", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, থানচি, Bandarban", en: "Upazila Statistical Office, Thanchi, Bandarban", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আখাউড়া, Brahmanbaria", en: "Upazila Statistical Office, Akhaura, Brahmanbaria", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাঞ্ছারামপুর, Brahmanbaria", en: "Upazila Statistical Office, Bancharampur, Brahmanbaria", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ব্রাহ্মণবাড়িয়া সদর, Brahmanbaria", en: "Upazila Statistical Office, Brahmanbaria Sadar, Brahmanbaria", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আশুগঞ্জ, Brahmanbaria", en: "Upazila Statistical Office, Ashuganj, Brahmanbaria", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কসবা, Brahmanbaria", en: "Upazila Statistical Office, Kasba, Brahmanbaria", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নবীনগর, Brahmanbaria", en: "Upazila Statistical Office, Nabinagar, Brahmanbaria", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নাসিরনগর, Brahmanbaria", en: "Upazila Statistical Office, Nasirnagar, Brahmanbaria", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সরাইল, Brahmanbaria", en: "Upazila Statistical Office, Sarail, Brahmanbaria", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বিজয়নগর, Brahmanbaria", en: "Upazila Statistical Office, Bijoynagar, Brahmanbaria", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চাঁদপুর সদর, Chandpur", en: "Upazila Statistical Office, Chandpur Sadar, Chandpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফরিদগঞ্জ, Chandpur", en: "Upazila Statistical Office, Faridganj, Chandpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হাজীগঞ্জ, Chandpur", en: "Upazila Statistical Office, Hajiganj, Chandpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হাইমচর, Chandpur", en: "Upazila Statistical Office, Haimchar, Chandpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কচুয়া, Chandpur", en: "Upazila Statistical Office, Kachua, Chandpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মতলব উত্তর, Chandpur", en: "Upazila Statistical Office, Matlab Uttar, Chandpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মতলব দক্ষিণ, Chandpur", en: "Upazila Statistical Office, Matlab Dakshin, Chandpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শাহরাস্তি, Chandpur", en: "Upazila Statistical Office, Shahrasti, Chandpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বরুড়া, Cumilla", en: "Upazila Statistical Office, Barura, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ব্রাহ্মণপাড়া, Cumilla", en: "Upazila Statistical Office, Brahmanpara, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বুড়িচং, Cumilla", en: "Upazila Statistical Office, Burichang, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চান্দিনা, Cumilla", en: "Upazila Statistical Office, Chandina, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চৌদ্দগ্রাম, Cumilla", en: "Upazila Statistical Office, Chauddagram, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দাউদকান্দি, Cumilla", en: "Upazila Statistical Office, Daudkandi, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দেবিদ্বার, Cumilla", en: "Upazila Statistical Office, Debidwar, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হোমনা, Cumilla", en: "Upazila Statistical Office, Homna, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কুমিল্লা সদর, Cumilla", en: "Upazila Statistical Office, Cumilla Sadar, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লাকসাম, Cumilla", en: "Upazila Statistical Office, Laksam, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মনোহরগঞ্জ, Cumilla", en: "Upazila Statistical Office, Monohorgonj, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মেঘনা, Cumilla", en: "Upazila Statistical Office, Meghna, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মুরাদনগর, Cumilla", en: "Upazila Statistical Office, Muradnagar, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নাঙ্গলকোট, Cumilla", en: "Upazila Statistical Office, Nangalkot, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তিতাস, Cumilla", en: "Upazila Statistical Office, Titas, Cumilla", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চকরিয়া, Cox's Bazar", en: "Upazila Statistical Office, Chakaria, Cox's Bazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কক্সবাজার সদর, Cox's Bazar", en: "Upazila Statistical Office, Cox's Bazar Sadar, Cox's Bazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কুতুবদিয়া, Cox's Bazar", en: "Upazila Statistical Office, Kutubdia, Cox's Bazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মহেশখালী, Cox's Bazar", en: "Upazila Statistical Office, Maheshkhali, Cox's Bazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পেকুয়া, Cox's Bazar", en: "Upazila Statistical Office, Pekua, Cox's Bazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রামু, Cox's Bazar", en: "Upazila Statistical Office, Ramu, Cox's Bazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, টেকনাফ, Cox's Bazar", en: "Upazila Statistical Office, Teknaf, Cox's Bazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, উখিয়া, Cox's Bazar", en: "Upazila Statistical Office, Ukhiya, Cox's Bazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ছাগলনাইয়া, Feni", en: "Upazila Statistical Office, Chhagalnaiya, Feni", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দাগনভূঞা, Feni", en: "Upazila Statistical Office, Daganbhuiyan, Feni", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফেনী সদর, Feni", en: "Upazila Statistical Office, Feni Sadar, Feni", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পরশুরাম, Feni", en: "Upazila Statistical Office, Parshuram, Feni", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সোনাগাজী, Feni", en: "Upazila Statistical Office, Sonagazi, Feni", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফুলগাজী, Feni", en: "Upazila Statistical Office, Fulgazi, Feni", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দীঘিনালা, Khagrachhari", en: "Upazila Statistical Office, Dighinala, Khagrachhari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, খাগড়াছড়ি সদর, Khagrachhari", en: "Upazila Statistical Office, Khagrachhari Sadar, Khagrachhari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লক্ষ্মীছড়ি, Khagrachhari", en: "Upazila Statistical Office, Lakshmichhari, Khagrachhari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মহালছড়ি, Khagrachhari", en: "Upazila Statistical Office, Mahalchhari, Khagrachhari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মানিকছড়ি, Khagrachhari", en: "Upazila Statistical Office, Manikchhari, Khagrachhari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মাটিরাঙ্গা, Khagrachhari", en: "Upazila Statistical Office, Matiranga, Khagrachhari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পানছড়ি, Khagrachhari", en: "Upazila Statistical Office, Panchhari, Khagrachhari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রামগড়, Khagrachhari", en: "Upazila Statistical Office, Ramgarh, Khagrachhari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চরগ্রাম, Lakshmipur", en: "Upazila Statistical Office, Chargram, Lakshmipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কমলনগর, Lakshmipur", en: "Upazila Statistical Office, Kamalnagar, Lakshmipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লক্ষ্মীপুর সদর, Lakshmipur", en: "Upazila Statistical Office, Lakshmipur Sadar, Lakshmipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রায়পুর, Lakshmipur", en: "Upazila Statistical Office, Raipur, Lakshmipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রামগঞ্জ, Lakshmipur", en: "Upazila Statistical Office, Ramganj, Lakshmipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রামগতি, Lakshmipur", en: "Upazila Statistical Office, Ramgati, Lakshmipur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বেগমগঞ্জ, Noakhali", en: "Upazila Statistical Office, Begumganj, Noakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চাটখিল, Noakhali", en: "Upazila Statistical Office, Chatkhil, Noakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কোম্পানীগঞ্জ, Noakhali", en: "Upazila Statistical Office, Companiganj, Noakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হাতিয়া, Noakhali", en: "Upazila Statistical Office, Hatiya, Noakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কবিরহাট, Noakhali", en: "Upazila Statistical Office, Kabirhat, Noakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নোয়াখালী সদর, Noakhali", en: "Upazila Statistical Office, Noakhali Sadar, Noakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সেনবাগ, Noakhali", en: "Upazila Statistical Office, Senbagh, Noakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সোনাইমুড়ী, Noakhali", en: "Upazila Statistical Office, Sonaimuri, Noakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সুবর্ণচর, Noakhali", en: "Upazila Statistical Office, Subarnachar, Noakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাঘাইছড়ি, Rangamati", en: "Upazila Statistical Office, Baghaichhari, Rangamati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বরকল, Rangamati", en: "Upazila Statistical Office, Barkal, Rangamati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কাপ্তাই, Rangamati", en: "Upazila Statistical Office, Kaptai, Rangamati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জুরাছড়ি, Rangamati", en: "Upazila Statistical Office, Juraichhari, Rangamati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লংগদু, Rangamati", en: "Upazila Statistical Office, Langadu, Rangamati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নানিয়ারচর, Rangamati", en: "Upazila Statistical Office, Naniarchar, Rangamati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাজস্থলী, Rangamati", en: "Upazila Statistical Office, Rajasthali, Rangamati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাঙ্গামাটি সদর, Rangamati", en: "Upazila Statistical Office, Rangamati Sadar, Rangamati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বিলাইছড়ি, Rangamati", en: "Upazila Statistical Office, Belaichhari, Rangamati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাগমারা, Rajshahi", en: "Upazila Statistical Office, Bagmara, Rajshahi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাঘা, Rajshahi", en: "Upazila Statistical Office, Bagha, Rajshahi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চারঘাট, Rajshahi", en: "Upazila Statistical Office, Charghat, Rajshahi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দুর্গাপুর, Rajshahi", en: "Upazila Statistical Office, Durgapur, Rajshahi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গোদাগাড়ী, Rajshahi", en: "Upazila Statistical Office, Godagari, Rajshahi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মোহনপুর, Rajshahi", en: "Upazila Statistical Office, Mohanpur, Rajshahi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পবা, Rajshahi", en: "Upazila Statistical Office, Paba, Rajshahi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পুঠিয়া, Rajshahi", en: "Upazila Statistical Office, Puthia, Rajshahi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তানোর, Rajshahi", en: "Upazila Statistical Office, Tanore, Rajshahi", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আদমদিঘী, Bogura", en: "Upazila Statistical Office, Adamdighi, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বগুড়া সদর, Bogura", en: "Upazila Statistical Office, Bogura Sadar, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ধুনট, Bogura", en: "Upazila Statistical Office, Dhunat, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দুপচাঁচিয়া, Bogura", en: "Upazila Statistical Office, Dupchanchia, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গাবতলী, Bogura", en: "Upazila Statistical Office, Gabtali, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কাহালু, Bogura", en: "Upazila Statistical Office, Kahaloo, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নন্দীগ্রাম, Bogura", en: "Upazila Statistical Office, Nandigram, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সারিয়াকান্দি, Bogura", en: "Upazila Statistical Office, Sariakandi, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শাজাহানপুর, Bogura", en: "Upazila Statistical Office, Shajahanpur, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শেরপুর, Bogura", en: "Upazila Statistical Office, Sherpur, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শিবগঞ্জ, Bogura", en: "Upazila Statistical Office, Shibganj, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সোনাতলা, Bogura", en: "Upazila Statistical Office, Sonatola, Bogura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভোলাহাট, Chapainawabganj", en: "Upazila Statistical Office, Bholahat, Chapainawabganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চাঁপাইনবাবগঞ্জ সদর, Chapainawabganj", en: "Upazila Statistical Office, Chapainawabganj Sadar, Chapainawabganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গোমস্তাপুর, Chapainawabganj", en: "Upazila Statistical Office, Gomastapur, Chapainawabganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নাচোল, Chapainawabganj", en: "Upazila Statistical Office, Nachole, Chapainawabganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শিবগঞ্জ, Chapainawabganj", en: "Upazila Statistical Office, Shibganj, Chapainawabganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আক্কেলপুর, Joypurhat", en: "Upazila Statistical Office, Akkelpur, Joypurhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জয়পুরহাট সদর, Joypurhat", en: "Upazila Statistical Office, Joypurhat Sadar, Joypurhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালাই, Joypurhat", en: "Upazila Statistical Office, Kalai, Joypurhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ক্ষেতলাল, Joypurhat", en: "Upazila Statistical Office, Khetlal, Joypurhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পাঁচবিবি, Joypurhat", en: "Upazila Statistical Office, Panchbibi, Joypurhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আত্রাই, Naogaon", en: "Upazila Statistical Office, Atrai, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাদলগাছী, Naogaon", en: "Upazila Statistical Office, Badalgachhi, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ধামইরহাট, Naogaon", en: "Upazila Statistical Office, Dhamoirhat, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মান্দা, Naogaon", en: "Upazila Statistical Office, Manda, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মহাদেবপুর, Naogaon", en: "Upazila Statistical Office, Mahadevpur, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নওগাঁ সদর, Naogaon", en: "Upazila Statistical Office, Naogaon Sadar, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নিয়ামতপুর, Naogaon", en: "Upazila Statistical Office, Niamatpur, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পত্নীতলা, Naogaon", en: "Upazila Statistical Office, Patnitala, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পোরশা, Naogaon", en: "Upazila Statistical Office, Porsha, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাণীনগর, Naogaon", en: "Upazila Statistical Office, Raninagar, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সাপাহার, Naogaon", en: "Upazila Statistical Office, Sapahar, Naogaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাগাতিপাড়া, Natore", en: "Upazila Statistical Office, Bagatipara, Natore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বড়াইগ্রাম, Natore", en: "Upazila Statistical Office, Baraigram, Natore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গুরুদাসপুর, Natore", en: "Upazila Statistical Office, Gurudaspur, Natore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লালপুর, Natore", en: "Upazila Statistical Office, Lalpur, Natore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নাটোর সদর, Natore", en: "Upazila Statistical Office, Natore Sadar, Natore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সিংড়া, Natore", en: "Upazila Statistical Office, Singra, Natore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আটঘরিয়া, Pabna", en: "Upazila Statistical Office, Atgharia, Pabna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বেড়া, Pabna", en: "Upazila Statistical Office, Bera, Pabna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভাঙ্গুড়া, Pabna", en: "Upazila Statistical Office, Bhangura, Pabna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চাটমোহর, Pabna", en: "Upazila Statistical Office, Chatmohar, Pabna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফরিদপুর, Pabna", en: "Upazila Statistical Office, Faridpur, Pabna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঈশ্বরদী, Pabna", en: "Upazila Statistical Office, Ishwardi, Pabna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পাবনা সদর, Pabna", en: "Upazila Statistical Office, Pabna Sadar, Pabna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সাঁথিয়া, Pabna", en: "Upazila Statistical Office, Santhia, Pabna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সুজানগর, Pabna", en: "Upazila Statistical Office, Sujanagar, Pabna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বেলকুচি, Sirajganj", en: "Upazila Statistical Office, Belkuchi, Sirajganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চৌহালী, Sirajganj", en: "Upazila Statistical Office, Chauhali, Sirajganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কামারখন্দ, Sirajganj", en: "Upazila Statistical Office, Kamarkhanda, Sirajganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কাজীপুর, Sirajganj", en: "Upazila Statistical Office, Kazipur, Sirajganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রায়গঞ্জ, Sirajganj", en: "Upazila Statistical Office, Raiganj, Sirajganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শাহজাদপুর, Sirajganj", en: "Upazila Statistical Office, Shahjadpur, Sirajganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সিরাজগঞ্জ সদর, Sirajganj", en: "Upazila Statistical Office, Sirajganj Sadar, Sirajganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তাড়াশ, Sirajganj", en: "Upazila Statistical Office, Tarash, Sirajganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, উল্লাপাড়া, Sirajganj", en: "Upazila Statistical Office, Ullapara, Sirajganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বটিয়াঘাটা, Khulna", en: "Upazila Statistical Office, Botiaghata, Khulna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দাকোপ, Khulna", en: "Upazila Statistical Office, Dacope, Khulna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ডুমুরিয়া, Khulna", en: "Upazila Statistical Office, Dumuria, Khulna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দিঘলিয়া, Khulna", en: "Upazila Statistical Office, Dighalia, Khulna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কয়রা, Khulna", en: "Upazila Statistical Office, Koyra, Khulna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পাইকগাছা, Khulna", en: "Upazila Statistical Office, Paikgachha, Khulna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফুলতলা, Khulna", en: "Upazila Statistical Office, Phultala, Khulna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রূপসা, Khulna", en: "Upazila Statistical Office, Rupsa, Khulna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তেরখাদা, Khulna", en: "Upazila Statistical Office, Terokhada, Khulna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাগেরহাট সদর, Bagerhat", en: "Upazila Statistical Office, Bagerhat Sadar, Bagerhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চিতলমারী, Bagerhat", en: "Upazila Statistical Office, Chitalmari, Bagerhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফকিরহাট, Bagerhat", en: "Upazila Statistical Office, Fakirhat, Bagerhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কচুয়া, Bagerhat", en: "Upazila Statistical Office, Kachua, Bagerhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মোল্লাহাট, Bagerhat", en: "Upazila Statistical Office, Mollahat, Bagerhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মোংলা, Bagerhat", en: "Upazila Statistical Office, Mongla, Bagerhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মোরেলগঞ্জ, Bagerhat", en: "Upazila Statistical Office, Morrelganj, Bagerhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রামপাল, Bagerhat", en: "Upazila Statistical Office, Rampal, Bagerhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সরণখোলা, Bagerhat", en: "Upazila Statistical Office, Sarankhola, Bagerhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আলমডাঙ্গা, Chuadanga", en: "Upazila Statistical Office, Alamdanga, Chuadanga", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চুয়াডাঙ্গা সদর, Chuadanga", en: "Upazila Statistical Office, Chuadanga Sadar, Chuadanga", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দামুড়হুদা, Chuadanga", en: "Upazila Statistical Office, Damurhuda, Chuadanga", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জীবননগর, Chuadanga", en: "Upazila Statistical Office, Jibannagar, Chuadanga", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, অভয়নগর, Jashore", en: "Upazila Statistical Office, Abhaynagar, Jashore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাঘারপাড়া, Jashore", en: "Upazila Statistical Office, Bagherpara, Jashore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চৌগাছা, Jashore", en: "Upazila Statistical Office, Chaugachha, Jashore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঝিকরগাছা, Jashore", en: "Upazila Statistical Office, Jhikargachha, Jashore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কেশবপুর, Jashore", en: "Upazila Statistical Office, Keshabpur, Jashore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, যশোর সদর, Jashore", en: "Upazila Statistical Office, Jashore Sadar, Jashore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মনিরামপুর, Jashore", en: "Upazila Statistical Office, Manirampur, Jashore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শার্শা, Jashore", en: "Upazila Statistical Office, Sharsha, Jashore", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হরিণাকুন্ডু, Jhenaidah", en: "Upazila Statistical Office, Harinakunda, Jhenaidah", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঝিনাইদহ সদর, Jhenaidah", en: "Upazila Statistical Office, Jhenaidah Sadar, Jhenaidah", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালীগঞ্জ, Jhenaidah", en: "Upazila Statistical Office, Kaliganj, Jhenaidah", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কোটচাঁদপুর, Jhenaidah", en: "Upazila Statistical Office, Kotchandpur, Jhenaidah", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মহেশপুর, Jhenaidah", en: "Upazila Statistical Office, Maheshpur, Jhenaidah", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শৈলকুপা, Jhenaidah", en: "Upazila Statistical Office, Shailkupa, Jhenaidah", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভেড়ামারা, Kushtia", en: "Upazila Statistical Office, Bheramara, Kushtia", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দৌলতপুর, Kushtia", en: "Upazila Statistical Office, Daulatpur, Kushtia", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, খোকসা, Kushtia", en: "Upazila Statistical Office, Khoksa, Kushtia", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কুমারখালী, Kushtia", en: "Upazila Statistical Office, Kumarkhali, Kushtia", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কুষ্টিয়া সদর, Kushtia", en: "Upazila Statistical Office, Kushtia Sadar, Kushtia", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মিরপুর, Kushtia", en: "Upazila Statistical Office, Mirpur, Kushtia", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মাগুরা সদর, Magura", en: "Upazila Statistical Office, Magura Sadar, Magura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মহম্মদপুর, Magura", en: "Upazila Statistical Office, Mohammadpur, Magura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শালিখা, Magura", en: "Upazila Statistical Office, Shalikha, Magura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শ্রীপুর, Magura", en: "Upazila Statistical Office, Sreepur, Magura", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গাংনী, Meherpur", en: "Upazila Statistical Office, Gangni, Meherpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মেহেরপুর সদর, Meherpur", en: "Upazila Statistical Office, Meherpur Sadar, Meherpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মুজিবনগর, Meherpur", en: "Upazila Statistical Office, Mujibnagar, Meherpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালিয়া, Narail", en: "Upazila Statistical Office, Kalia, Narail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লোহাগড়া, Narail", en: "Upazila Statistical Office, Lohagara, Narail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নড়াইল সদর, Narail", en: "Upazila Statistical Office, Narail Sadar, Narail", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আশাশুনি, Satkhira", en: "Upazila Statistical Office, Assasuni, Satkhira", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দেবহাটা, Satkhira", en: "Upazila Statistical Office, Debhata, Satkhira", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কলারোয়া, Satkhira", en: "Upazila Statistical Office, Kalaroa, Satkhira", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালীগঞ্জ, Satkhira", en: "Upazila Statistical Office, Kaliganj, Satkhira", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সাতক্ষীরা সদর, Satkhira", en: "Upazila Statistical Office, Satkhira Sadar, Satkhira", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শ্যামনগর, Satkhira", en: "Upazila Statistical Office, Shyamnagar, Satkhira", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তালা, Satkhira", en: "Upazila Statistical Office, Tala, Satkhira", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আগৈলঝড়া, Barishal", en: "Upazila Statistical Office, Agailjhara, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাবুগঞ্জ, Barishal", en: "Upazila Statistical Office, Babuganj, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাকেরগঞ্জ, Barishal", en: "Upazila Statistical Office, Bakerganj, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বানারীপাড়া, Barishal", en: "Upazila Statistical Office, Banaripara, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বরিশাল সদর, Barishal", en: "Upazila Statistical Office, Barishal Sadar, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গৌরনদী, Barishal", en: "Upazila Statistical Office, Gournadi, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হিজলা, Barishal", en: "Upazila Statistical Office, Hizla, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মেহেন্দিগঞ্জ, Barishal", en: "Upazila Statistical Office, Mehendiganj, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মুলাদী, Barishal", en: "Upazila Statistical Office, Muladi, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, উজিরপুর, Barishal", en: "Upazila Statistical Office, Wazirpur, Barishal", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আমতলী, Barguna", en: "Upazila Statistical Office, Amtali, Barguna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বামনা, Barguna", en: "Upazila Statistical Office, Bamna, Barguna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বরগুনা সদর, Barguna", en: "Upazila Statistical Office, Barguna Sadar, Barguna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বেতাগী, Barguna", en: "Upazila Statistical Office, Betagi, Barguna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পাথরঘাটা, Barguna", en: "Upazila Statistical Office, Patharghata, Barguna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তালতলী, Barguna", en: "Upazila Statistical Office, Taltali, Barguna", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভোলা সদর, Bhola", en: "Upazila Statistical Office, Bhola Sadar, Bhola", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বোরহানউদ্দিন, Bhola", en: "Upazila Statistical Office, Burhanuddin, Bhola", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চরফ্যাশন, Bhola", en: "Upazila Statistical Office, Charfasson, Bhola", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দৌলতখান, Bhola", en: "Upazila Statistical Office, Daulatkhan, Bhola", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লালমোহন, Bhola", en: "Upazila Statistical Office, Lalmohan, Bhola", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মনপুরা, Bhola", en: "Upazila Statistical Office, Manpura, Bhola", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তজুমদ্দিন, Bhola", en: "Upazila Statistical Office, Tazumuddin, Bhola", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঝালকাঠি সদর, Jhalokati", en: "Upazila Statistical Office, Jhalokati Sadar, Jhalokati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কাঠালিয়া, Jhalokati", en: "Upazila Statistical Office, Kathalia, Jhalokati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নলছিটি, Jhalokati", en: "Upazila Statistical Office, Nalchity, Jhalokati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাজাপুর, Jhalokati", en: "Upazila Statistical Office, Rajapur, Jhalokati", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাউফল, Patuakhali", en: "Upazila Statistical Office, Bauphal, Patuakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দশমিনা, Patuakhali", en: "Upazila Statistical Office, Dashmina, Patuakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গলাচিপা, Patuakhali", en: "Upazila Statistical Office, Galachipa, Patuakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কলাপাড়া, Patuakhali", en: "Upazila Statistical Office, Kalapara, Patuakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মির্জাগঞ্জ, Patuakhali", en: "Upazila Statistical Office, Mirzaganj, Patuakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পটুয়াখালী সদর, Patuakhali", en: "Upazila Statistical Office, Patuakhali Sadar, Patuakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাঙ্গাবালী, Patuakhali", en: "Upazila Statistical Office, Rangabali, Patuakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দুমকি, Patuakhali", en: "Upazila Statistical Office, Dumki, Patuakhali", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভান্ডারিয়া, Pirojpur", en: "Upazila Statistical Office, Bhandaria, Pirojpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কাউখালী, Pirojpur", en: "Upazila Statistical Office, Kaukhali, Pirojpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মঠবাড়িয়া, Pirojpur", en: "Upazila Statistical Office, Mathbaria, Pirojpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নাজিরপুর, Pirojpur", en: "Upazila Statistical Office, Nazirpur, Pirojpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নেছারাবদ, Pirojpur", en: "Upazila Statistical Office, Nesarabad, Pirojpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পিরোজপুর সদর, Pirojpur", en: "Upazila Statistical Office, Pirojpur Sadar, Pirojpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জিয়ানগর, Pirojpur", en: "Upazila Statistical Office, Zianagar, Pirojpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বালাগঞ্জ, Sylhet", en: "Upazila Statistical Office, Balaganj, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বিয়ানীবাজার, Sylhet", en: "Upazila Statistical Office, Beanibazar, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বিশ্বনাথ, Sylhet", en: "Upazila Statistical Office, Bishwanath, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কোম্পানীগঞ্জ, Sylhet", en: "Upazila Statistical Office, Companiganj, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দক্ষিণ সুরমা, Sylhet", en: "Upazila Statistical Office, Dakshin Surma, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফেঞ্চুগঞ্জ, Sylhet", en: "Upazila Statistical Office, Fenchuganj, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গোলাপগঞ্জ, Sylhet", en: "Upazila Statistical Office, Golapganj, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গোয়াইনঘাট, Sylhet", en: "Upazila Statistical Office, Gowainghat, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জৈন্তাপুর, Sylhet", en: "Upazila Statistical Office, Jaintiapur, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কানাইঘাট, Sylhet", en: "Upazila Statistical Office, Kanaighat, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সিলেট সদর, Sylhet", en: "Upazila Statistical Office, Sylhet Sadar, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জকিগঞ্জ, Sylhet", en: "Upazila Statistical Office, Zakiganj, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ওসমানীনগর, Sylhet", en: "Upazila Statistical Office, Osmaninagar, Sylhet", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আজমিরীগঞ্জ, Habiganj", en: "Upazila Statistical Office, Ajmiriganj, Habiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বাহুবল, Habiganj", en: "Upazila Statistical Office, Bahubal, Habiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বানিয়াচং, Habiganj", en: "Upazila Statistical Office, Baniachong, Habiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চুনারুঘাট, Habiganj", en: "Upazila Statistical Office, Chunarughat, Habiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হবিগঞ্জ সদর, Habiganj", en: "Upazila Statistical Office, Habiganj Sadar, Habiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লাখাই, Habiganj", en: "Upazila Statistical Office, Lakhai, Habiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মাধবপুর, Habiganj", en: "Upazila Statistical Office, Madhabpur, Habiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নবীগঞ্জ, Habiganj", en: "Upazila Statistical Office, Nabiganj, Habiganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বড়লেখা, Moulvibazar", en: "Upazila Statistical Office, Barlekha, Moulvibazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জুড়ী, Moulvibazar", en: "Upazila Statistical Office, Juri, Moulvibazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কমলগঞ্জ, Moulvibazar", en: "Upazila Statistical Office, Kamalganj, Moulvibazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কুলাউড়া, Moulvibazar", en: "Upazila Statistical Office, Kulaura, Moulvibazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মৌলভীবাজার সদর, Moulvibazar", en: "Upazila Statistical Office, Moulvibazar Sadar, Moulvibazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাজনগর, Moulvibazar", en: "Upazila Statistical Office, Rajnagar, Moulvibazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শ্রীমঙ্গল, Moulvibazar", en: "Upazila Statistical Office, Sreemangal, Moulvibazar", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বিশ্বম্ভরপুর, Sunamganj", en: "Upazila Statistical Office, Bishwambarpur, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ছাতক, Sunamganj", en: "Upazila Statistical Office, Chhatak, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দক্ষিণ সুনামগঞ্জ, Sunamganj", en: "Upazila Statistical Office, Dakshin Sunamganj, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দিরাই, Sunamganj", en: "Upazila Statistical Office, Derai, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ধর্মপাশা, Sunamganj", en: "Upazila Statistical Office, Dharmapasha, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দোয়ারাবাজার, Sunamganj", en: "Upazila Statistical Office, Dowarabazar, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জগন্নাথপুর, Sunamganj", en: "Upazila Statistical Office, Jagannathpur, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জামালগঞ্জ, Sunamganj", en: "Upazila Statistical Office, Jamalganj, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সুনামগঞ্জ সদর, Sunamganj", en: "Upazila Statistical Office, Sunamganj Sadar, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শাল্লা, Sunamganj", en: "Upazila Statistical Office, Shalla, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তাহিরপুর, Sunamganj", en: "Upazila Statistical Office, Tahirpur, Sunamganj", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বদরগঞ্জ, Rangpur", en: "Upazila Statistical Office, Badarganj, Rangpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গঙ্গাচড়া, Rangpur", en: "Upazila Statistical Office, Gangachara, Rangpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কাউনিয়া, Rangpur", en: "Upazila Statistical Office, Kaunia, Rangpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মিঠাপুকুর, Rangpur", en: "Upazila Statistical Office, Mithapukur, Rangpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পীরগঞ্জ, Rangpur", en: "Upazila Statistical Office, Pirgachha, Rangpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রংপুর সদর, Rangpur", en: "Upazila Statistical Office, Rangpur Sadar, Rangpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পীরগঞ্জ, Rangpur", en: "Upazila Statistical Office, Pirganj, Rangpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তারাগঞ্জ, Rangpur", en: "Upazila Statistical Office, Taraganj, Rangpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বিরামপুর, Dinajpur", en: "Upazila Statistical Office, Birampur, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বীরগঞ্জ, Dinajpur", en: "Upazila Statistical Office, Birganj, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বোচাগঞ্জ, Dinajpur", en: "Upazila Statistical Office, Bochaganj, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চিরিরবন্দর, Dinajpur", en: "Upazila Statistical Office, Chirirbandar, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দিনাজপুর সদর, Dinajpur", en: "Upazila Statistical Office, Dinajpur Sadar, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফুলবাড়ী, Dinajpur", en: "Upazila Statistical Office, Phulbari, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঘোড়াঘাট, Dinajpur", en: "Upazila Statistical Office, Ghoraghat, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হাকিমপুর, Dinajpur", en: "Upazila Statistical Office, Hakimpur, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কাহারোল, Dinajpur", en: "Upazila Statistical Office, Kaharole, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, খানসামা, Dinajpur", en: "Upazila Statistical Office, Khansama, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নবাবগঞ্জ, Dinajpur", en: "Upazila Statistical Office, Nawabganj, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পার্বতীপুর, Dinajpur", en: "Upazila Statistical Office, Parbatipur, Dinajpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফুলছড়ি, Gaibandha", en: "Upazila Statistical Office, Fulchhari, Gaibandha", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গাইবান্ধা সদর, Gaibandha", en: "Upazila Statistical Office, Gaibandha Sadar, Gaibandha", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গোবিন্দগঞ্জ, Gaibandha", en: "Upazila Statistical Office, Gobindaganj, Gaibandha", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পলাশবাড়ী, Gaibandha", en: "Upazila Statistical Office, Palashbari, Gaibandha", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সাদুল্লাপুর, Gaibandha", en: "Upazila Statistical Office, Sadullapur, Gaibandha", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সাঘাটা, Gaibandha", en: "Upazila Statistical Office, Saghata, Gaibandha", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সুন্দরগঞ্জ, Gaibandha", en: "Upazila Statistical Office, Sundarganj, Gaibandha", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভুরুঙ্গামারী, Kurigram", en: "Upazila Statistical Office, Bhurungamari, Kurigram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চর রাজীবপুর, Kurigram", en: "Upazila Statistical Office, Char Rajibpur, Kurigram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, চিলমারী, Kurigram", en: "Upazila Statistical Office, Chilmari, Kurigram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফুলবাড়ী, Kurigram", en: "Upazila Statistical Office, Phulbari, Kurigram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কুড়িগ্রাম সদর, Kurigram", en: "Upazila Statistical Office, Kurigram Sadar, Kurigram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নাগেশ্বরী, Kurigram", en: "Upazila Statistical Office, Nageshwari, Kurigram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রাজারহাট, Kurigram", en: "Upazila Statistical Office, Rajarhat, Kurigram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রৌমারী, Kurigram", en: "Upazila Statistical Office, Raumari, Kurigram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, উলিপুর, Kurigram", en: "Upazila Statistical Office, Ulipur, Kurigram", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আদিতমারী, Lalmonirhat", en: "Upazila Statistical Office, Aditmari, Lalmonirhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হাতীবান্ধা, Lalmonirhat", en: "Upazila Statistical Office, Hatibandha, Lalmonirhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কালীগঞ্জ, Lalmonirhat", en: "Upazila Statistical Office, Kaliganj, Lalmonirhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, লালমনিরহাট সদর, Lalmonirhat", en: "Upazila Statistical Office, Lalmonirhat Sadar, Lalmonirhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পাটগ্রাম, Lalmonirhat", en: "Upazila Statistical Office, Patgram, Lalmonirhat", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ডিমলা, Nilphamari", en: "Upazila Statistical Office, Dimla, Nilphamari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ডোমার, Nilphamari", en: "Upazila Statistical Office, Domar, Nilphamari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জলঢাকা, Nilphamari", en: "Upazila Statistical Office, Jaldhaka, Nilphamari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কিশোরগঞ্জ, Nilphamari", en: "Upazila Statistical Office, Kishoreganj, Nilphamari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নীলফামারী সদর, Nilphamari", en: "Upazila Statistical Office, Nilphamari Sadar, Nilphamari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সৈয়দপুর, Nilphamari", en: "Upazila Statistical Office, Saidpur, Nilphamari", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আটোয়ারী, Panchagarh", en: "Upazila Statistical Office, Atwari, Panchagarh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বোদা, Panchagarh", en: "Upazila Statistical Office, Boda, Panchagarh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দেবীগঞ্জ, Panchagarh", en: "Upazila Statistical Office, Debiganj, Panchagarh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পঞ্চগড় সদর, Panchagarh", en: "Upazila Statistical Office, Panchagarh Sadar, Panchagarh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, তেতুলিয়া, Panchagarh", en: "Upazila Statistical Office, Tetulia, Panchagarh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বালিয়াডাঙ্গী, Thakurgaon", en: "Upazila Statistical Office, Baliadangi, Thakurgaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হরিপুর, Thakurgaon", en: "Upazila Statistical Office, Haripur, Thakurgaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পীরগঞ্জ, Thakurgaon", en: "Upazila Statistical Office, Pirganj, Thakurgaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, রানীশংকৈল, Thakurgaon", en: "Upazila Statistical Office, Ranisankail, Thakurgaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঠাকুরগাঁও সদর, Thakurgaon", en: "Upazila Statistical Office, Thakurgaon Sadar, Thakurgaon", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ভালুকা, Mymensingh", en: "Upazila Statistical Office, Bhaluka, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ধোবাউড়া, Mymensingh", en: "Upazila Statistical Office, Dhobaura, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফুলবাড়ীয়া, Mymensingh", en: "Upazila Statistical Office, Fulbaria, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গফরগাঁও, Mymensingh", en: "Upazila Statistical Office, Gaffargaon, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, গৌরীপুর, Mymensingh", en: "Upazila Statistical Office, Gouripur, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, হালুয়াঘাট, Mymensingh", en: "Upazila Statistical Office, Haluaghat, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঈশ্বরগঞ্জ, Mymensingh", en: "Upazila Statistical Office, Ishwarganj, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মুক্তাগাছা, Mymensingh", en: "Upazila Statistical Office, Muktagachha, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ময়মনসিংহ সদর, Mymensingh", en: "Upazila Statistical Office, Mymensingh Sadar, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নান্দাইল, Mymensingh", en: "Upazila Statistical Office, Nandail, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ফুলপুর, Mymensingh", en: "Upazila Statistical Office, Phulpur, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ত্রিশাল, Mymensingh", en: "Upazila Statistical Office, Trishal, Mymensingh", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বকশীগঞ্জ, Jamalpur", en: "Upazila Statistical Office, Baksiganj, Jamalpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দেওয়ানগঞ্জ, Jamalpur", en: "Upazila Statistical Office, Dewanganj, Jamalpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ইসলামপুর, Jamalpur", en: "Upazila Statistical Office, Islampur, Jamalpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, জামালপুর সদর, Jamalpur", en: "Upazila Statistical Office, Jamalpur Sadar, Jamalpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মাদারগঞ্জ, Jamalpur", en: "Upazila Statistical Office, Madarganj, Jamalpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মেলান্দহ, Jamalpur", en: "Upazila Statistical Office, Melandah, Jamalpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, সরিষাবাড়ী, Jamalpur", en: "Upazila Statistical Office, Sarishabari, Jamalpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, ঝিনাইগাতী, Sherpur", en: "Upazila Statistical Office, Jhenaigati, Sherpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নকলা, Sherpur", en: "Upazila Statistical Office, Nakla, Sherpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নালিতাবাড়ী, Sherpur", en: "Upazila Statistical Office, Nalitabari, Sherpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শেরপুর সদর, Sherpur", en: "Upazila Statistical Office, Sherpur Sadar, Sherpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, শ্রীবরদী, Sherpur", en: "Upazila Statistical Office, Sreebordi, Sherpur", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, আটপাড়া, Netrokona", en: "Upazila Statistical Office, Atpara, Netrokona", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, বারহাট্টা, Netrokona", en: "Upazila Statistical Office, Barhatta, Netrokona", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, দুর্গাপুর, Netrokona", en: "Upazila Statistical Office, Durgapur, Netrokona", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, খালিয়াজুরী, Netrokona", en: "Upazila Statistical Office, Khaliajuri, Netrokona", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কলমাকান্দা, Netrokona", en: "Upazila Statistical Office, Kalmakanda, Netrokona", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, কেন্দুয়া, Netrokona", en: "Upazila Statistical Office, Kendua, Netrokona", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মদন, Netrokona", en: "Upazila Statistical Office, Madan, Netrokona", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, মোহনগঞ্জ, Netrokona", en: "Upazila Statistical Office, Mohanganj, Netrokona", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, নেত্রকোনা সদর, Netrokona", en: "Upazila Statistical Office, Netrokona Sadar, Netrokona", type: "Upazila" },
  { bn: "উপজেলা পরিসংখ্যান অফিস, পূর্বধলা, Netrokona", en: "Upazila Statistical Office, Purbadhala, Netrokona", type: "Upazila" }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { bbsOffices };
}
