- name: Generate Icons and Splash
        run: |
          # আইকন জেনারেটর টুল ইনস্টল
          npm install @capacitor/assets --save-dev
          
          # আইকন জেনারেট করা (এটি অটোমেটিক সব সাইজ তৈরি করে দেবে)
          npx capacitor-assets generate --android
